### ISSUE TITLE
PermissionError 

### ISSUE THREAD

**Issue by epifanio** [brendan-rius/jupyter-c-kernel#12] opened 2016-06-07 02:57 UTC
Hi, I just installed the `jupyter-c-kernel` on my jupyterhub server (i installed it with sudo to have the kernel available for all the users).
When I try to execute the simple hello world example i got this log in the notebook shell output:

```
[I 2016-06-07 04:51:13.171 epinux kernelmanager:89] Kernel started: 22a3c6c7-8932-4cf2-b377-b4f33f571430
gcc: error: /usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/jupyter_c_kernel/../resources/master.c: No such file or directory
[IPKernelApp] ERROR | UNKNOWN MESSAGE TYPE: 'comm_open'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/jupyter_c_kernel/kernel.py", line 135, in do_execute
    p = self.create_jupyter_subprocess([self.master_path, binary_file.name])
  File "/usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/jupyter_c_kernel/kernel.py", line 112, in create_jupyter_subprocess
    lambda contents: self._write_to_stderr(contents.decode()))
  File "/usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/jupyter_c_kernel/kernel.py", line 25, in __init__
    super().__init__(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, bufsize=0)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/jupyter_c_kernel/kernel.py", line 135, in do_execute
    p = self.create_jupyter_subprocess([self.master_path, binary_file.name])
  File "/usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/jupyter_c_kernel/kernel.py", line 112, in create_jupyter_subprocess
    lambda contents: self._write_to_stderr(contents.decode()))
  File "/usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/jupyter_c_kernel/kernel.py", line 25, in __init__
    super().__init__(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, bufsize=0)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

I guess is an issue on how I installed the kernel, thanks for looking into this.

**Comment by brendan-rius** [comment] 2016-06-07 10:59
Hi thank you for the feedback, could you tell me how you tried to install it exactly?

**Comment by epifanio** [comment] 2016-06-07 12:50
Hi @brendan-rius 
I installed *jupyter-c-kernel* on a Linux server running *debian sid* with system *python3 v 3.5.1+*  and *jupter v 4.1.0* using:

```
mkdir dev
cd dev
git clone https://github.com/brendan-rius/jupyter-c-kernel
cd jupyter-c-kernel
sudo python3 setu.py install
```

**Comment by epifanio** [comment] 2016-06-11 05:08
Hi @brendan-rius , is the installation process correct? should I repeat it or change something?
I updated my clone and re-tried the installation (I also executed the install script ) but i still have permission error. Looking into the source now. Thanks for any advice.

**Comment by epifanio** [comment] 2016-06-11 05:15
It seems the error was generated by a missed resource directory. Ii copied it from the ```src root``` into: 
```
/usr/local/lib/python3.5/dist-packages/jupyter_c_kernel-1.0.0-py3.5.egg/
```
And now hello world works fine! :) I'll test with more complex **c** code and I'll report here if any problem. Thanks!

**Comment by brendan-rius** [comment] 2016-06-13 12:49
Thank you for raising that issue; it might be because of the way you installed it (using directly the `setup.py` and not `pip`). Maybe this way of doing does not copy the resource files. If so, it is a bug to fix, and I will take a look as soon as I can.

I am not closing the issue

**Comment by zbeekman** [comment] 2017-06-05 19:26
There are problems in the docker image too... the sudo/root install makes certain thinks owned by root when they should be owned by $NB_USER.

**Comment by brendan-rius** [comment] 2017-08-10 15:14
Fixed in the new version (1.2.0)
Please refer to the README on how to install :)

**Closed by brendan-rius** 2017-08-10 15:14 UTC
Labels: bug

**Comment by nickyfoto** [comment] 2017-08-17 15:31
I installed c-kernel with pip3 on OS X 10.12.6 it still produces `PermissionError: [Errno 13] Permission denied` error when I try to run C code.

I copied the folder and file `resources/master.c` to `/usr/local/lib/python3.6/site-packages/` to solve this problem

**Comment by brendan-rius** [comment] 2017-08-17 20:19
Can you run 

```
pip show jupyter-c-kernel
```

and give me the version number you are using? Make sure it is at least 1.2.0
If it is not, please upgrade it:

```
pip install --upgrade jupyter-c-kernel
```

Tell me if it works

**Comment by nickyfoto** [comment] 2017-08-18 01:08
Yes I installed 1.2.0. The same problem happens when I try to install it on a Ubuntu server on Digital Ocean. The docker works fine.

```
➜  ~ pip3 show jupyter-c-kernel
Name: jupyter-c-kernel
Version: 1.2.0
Summary: Minimalistic C kernel for Jupyter
Home-page: https://github.com/brendanrius/jupyter-c-kernel/
Author: Brendan Rius
Author-email: ping@brendan-rius.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/site-packages
Requires:
```

**Comment by brendan-rius** [comment] 2017-08-18 09:48
Just created a DO droplet on Ubuntu 16.04.3 x64, then ran the following commands:

```
apt update
apt install python3-pip
pip3 install jupyter
pip3 install jupyter-c-kernel
install_c_kernel
```

and it works fines.

Anyway, it looks like you have a permission problem. Could you try to run 

```
install_c_kernel --user
```

That will install the kernel for only the current user, and not globally. That is what the Docker does

**Comment by snailkn** [comment] 2017-08-19 13:08
I have the same trouble in on OS X 10.12.6, I found the dir `resources` is not installed successfully. Finally I copy the dir to the target dir and solve the bug.

**Comment by brendan-rius** [comment] 2017-08-23 12:01
This is weird, do you have any error message or weird behaviour while installing?

Could you please send me the exact installation steps you used so I can try to reproduce the same thing? (it works on my Mac, and on DO)

**Comment by albertmundu** [comment] 2017-10-12 20:57
I am getting the same error. I installed using the readme file
```
pip install jupyter-c-kernel
install_c_kernel
```
Because I am using virtualenv I used
```
(deep) user jupyter_programs$ install_c_kernel --sys-prefix
Installing IPython kernel spec

(deep) user jupyter_programs$ install_c_kernel --help
usage: install_c_kernel [-h] [--user | --sys-prefix | --prefix PREFIX]

Install KernelSpec for C Kernel

optional arguments:
  -h, --help       show this help message and exit
  --user           Install KernelSpec in user homedirectory
  --sys-prefix     Install KernelSpec in sys.prefix. Useful in conda /
                   virtualenv
  --prefix PREFIX  Install KernelSpec in this prefix
```
#### Error Log 
```
IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/user/virtualenvs/deep/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/user/virtualenvs/deep/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/user/virtualenvs/deep/lib/python3.5/site-packages/jupyter_c_kernel/kernel.py", line 161, in do_execute
    p = self.create_jupyter_subprocess([self.master_path, binary_file.name] + magics['args'])
  File "/home/user/virtualenvs/deep/lib/python3.5/site-packages/jupyter_c_kernel/kernel.py", line 113, in create_jupyter_subprocess
    lambda contents: self._write_to_stderr(contents.decode()))
  File "/home/user/virtualenvs/deep/lib/python3.5/site-packages/jupyter_c_kernel/kernel.py", line 26, in __init__
    super().__init__(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, bufsize=0)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```
**I cannot find a valuable solution to this**

**Comment by indajuan** [comment] 2017-11-07 10:00
Hello,
Could you please help me with the installation on Ubuntu 17.04? 
I followed the instructions:
- pip install jupyter-c-kernel
- install_c_kernel

install_c_kernel returned an error, permission denied.

So I tried with install_c_kernel --user and it worked out fine. 

Nevertheless, if I run the notebook with the hello world example ( or any code), the kernel does not return any output, it just runs but it does not return anything. It does however, send error messages if the code is wrong. 

Thanks,
