### ISSUE TITLE
issue when running

### ISSUE THREAD

**Issue by andreapago** [brendan-rius/jupyter-c-kernel#13] opened 2016-06-07 11:12 UTC
Hi Brendan, 

I hit the following when I run jupyterhub and the C kernel you provide

`No module named jupyter_c_kernel`

and in the notebook it keeps trying to restart the kernel and getting the message again....
Any ideas about the problem?

Many thanks in advance.

**Comment by brendan-rius** [comment] 2016-06-07 11:15
Hi,

It looks like `jupyter_c_kernel` is not installed. Have you ran `pip install jupyter-c-kernel` before installing the kernel ?
If it does not work with that, could you please tell me step-by-step how you installed it, so I can try to reproduce the bug?

Thank you!

**Comment by andreapago** [comment] 2016-06-07 11:48
hi Thanks for your reply.

I have done the following: first tried the simple "Easy installation for Unix user:" didn't work was not finding some of the command to be issued 

> :: Cloning Jupyter C-kernel...
Cloning into 'jupyter-c-kernel'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Done.
:: Installing python module C kernel.
sudo: pip: command not found
Done.
:: Installing kernel specification
sh: line 19: cd: jupyter-c-kernel: No such file or directory
sudo: jupyter-kernelspec: command not found
Done.
Completed! Installation successful. You can type jupyter-notebook and be happy

Then I did 

> pip install jupyter-c-kernel
Collecting jupyter-c-kernel
  Downloading jupyter_c_kernel-1.0.0.tar.gz
Installing collected packages: jupyter-c-kernel
  Running setup.py install for jupyter-c-kernel ... done

then I repeated the process by cloning the repository (the cloning via ssh failed)

> git clone https://github.com/brendan-rius/jupyter-c-kernel.git/
pip install jupyter-c-kernel
cd jupyter-c-kernel
jupyter-kernelspec install c_spec/

hope it clears the situations

**Comment by andreapago** [comment] 2016-06-07 21:35
Hi Brendan, any news on that issue? How should I proceed? Any idea? Many thanks in advance.

**Comment by brendan-rius** [comment] 2016-06-08 09:31
Could you try the steps below and tell me if it works?

```bash
pip install jupyer-c-kernel
git clone https://github.com/brendan-rius/jupyter-c-kernel.git/
cd jupyter-c-kernel
jupyter-kernelspec install c_spec/
```

**Comment by andreapago** [comment] 2016-06-08 10:04
Hi Brendan,

I have just followed your steps, it does not work the kernel keeps restarting or so, here is the debug info I get from my JupyterHub:

```
[W 2016-06-08 09:55:54.419 knmi log:47] 404 GET /user/knmi/nbextensions/widgets/notebook/js/extension.js?v=20160608095544 (127.0.0.1) 13.25ms referer=http://127.0.0.1:8000/user/knmi/notebooks/Untitled4.ipynb?kernel_name=c_spec
[I 2016-06-08 09:55:54.546 knmi kernelmanager:89] Kernel started: 3d16f4c6-b2ac-4764-bed2-2a4481514476
/usr/bin/python3: No module named jupyter_c_kernel
[I 2016-06-08 09:55:57.547 knmi restarter:103] KernelRestarter: restarting kernel (1/5)
/usr/bin/python3: No module named jupyter_c_kernel
[I 2016-06-08 09:56:00.555 knmi restarter:103] KernelRestarter: restarting kernel (2/5)
/usr/bin/python3: No module named jupyter_c_kernel
[I 2016-06-08 09:56:03.563 knmi restarter:103] KernelRestarter: restarting kernel (3/5)
/usr/bin/python3: No module named jupyter_c_kernel
[W 2016-06-08 09:56:04.770 knmi handlers:223] Timeout waiting for kernel_info reply from 3d16f4c6-b2ac-4764-bed2-2a4481514476
[I 2016-06-08 09:56:06.569 knmi restarter:103] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 3d16f4c6-b2ac-4764-bed2-2a4481514476 restarted
/usr/bin/python3: No module named jupyter_c_kernel
[W 2016-06-08 09:56:09.590 knmi restarter:95] KernelRestarter: restart failed
[W 2016-06-08 09:56:09.590 knmi kernelmanager:54] Kernel 3d16f4c6-b2ac-4764-bed2-2a4481514476 died, removing from map.
ERROR:root:kernel 3d16f4c6-b2ac-4764-bed2-2a4481514476 restarted failed!
[W 2016-06-08 09:56:09.639 knmi handlers:462] Kernel deleted before session
[W 2016-06-08 09:56:09.640 knmi log:47] 410 DELETE /user/knmi/api/sessions/d901265e-e830-46e4-9c44-3ca9abbe1427 (127.0.0.1) 2.28ms referer=http://127.0.0.1:8000/user/knmi/notebooks/Untitled4.ipynb?kernel_name=c_spec
[W 2016-06-08 09:56:14.348 knmi handlers:462] Session not found: session_id='d901265e-e830-46e4-9c44-3ca9abbe1427'
[W 2016-06-08 09:56:14.349 knmi log:47] 404 DELETE /user/knmi/api/sessions/d901265e-e830-46e4-9c44-3ca9abbe1427 (127.0.0.1) 2.89ms referer=http://127.0.0.1:8000/user/knmi/notebooks/Untitled4.ipynb?kernel_name=c_spec
[I 2016-06-08 09:56:14.415 knmi kernelmanager:89] Kernel started: 31ec71c6-0c01-45f5-969b-de84b81cb322
/usr/bin/python3: No module named jupyter_c_kernel
[I 2016-06-08 09:56:17.417 knmi restarter:103] KernelRestarter: restarting kernel (1/5)
/usr/bin/python3: No module named jupyter_c_kernel
[I 2016-06-08 09:56:20.425 knmi restarter:103] KernelRestarter: restarting kernel (2/5)
/usr/bin/python3: No module named jupyter_c_kernel
[I 2016-06-08 09:56:23.433 knmi restarter:103] KernelRestarter: restarting kernel (3/5)
/usr/bin/python3: No module named jupyter_c_kernel
[W 2016-06-08 09:56:24.780 knmi handlers:223] Timeout waiting for kernel_info reply from 31ec71c6-0c01-45f5-969b-de84b81cb322
[I 2016-06-08 09:56:26.440 knmi restarter:103] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 31ec71c6-0c01-45f5-969b-de84b81cb322 restarted
/usr/bin/python3: No module named jupyter_c_kernel
[W 2016-06-08 09:56:29.459 knmi restarter:95] KernelRestarter: restart failed
[W 2016-06-08 09:56:29.460 knmi kernelmanager:54] Kernel 31ec71c6-0c01-45f5-969b-de84b81cb322 died, removing from map.
ERROR:root:kernel 31ec71c6-0c01-45f5-969b-de84b81cb322 restarted failed!
[W 2016-06-08 09:56:29.539 knmi handlers:462] Kernel deleted before session
[W 2016-06-08 09:56:29.540 knmi log:47] 410 DELETE /user/knmi/api/sessions/9dd3ee70-b3d7-482d-96fb-104c68160e0d (127.0.0.1) 2.48ms referer=http://127.0.0.1:8000/user/knmi/notebooks/Untitled4.ipynb?kernel_name=c_spec
```

**Comment by andreapago** [comment] 2016-06-09 06:17
Hi Brendan,

I solved it: the kernel was seraching for python3 (and finding it) in a location where the additional libraries are not installed. I just replaced that with a link to the proper location of python3 where all the packages are also installed.

thanks & cheers

**Comment by brendan-rius** [comment] 2016-06-11 11:20
Glad you solved the problem!
I am closing the issue :)

**Closed by brendan-rius** 2016-06-11 11:20 UTC

**Comment by hediharzallah** [comment] 2016-12-21 09:36
To install it for python3 you can use : sudo pip3 install jupyter_c_kernel

**Comment by wijanarto** [comment] 2018-09-07 01:59
I have installed perfecly, but when i run your hello world example code, nothing happen, no output printed out, Why ?
`#include <stdio.h>
int main(){
printf("Hello World\n");
}` 
this is compiler i have
`gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0`
when i choose julia as kernel, jupyter running well
